swagger: "2.0"
info:
  title: AIR api
  description: The AIR api consist api related to air application's online functionality
  version: 1.0
  contact:
    email: sidhant@thelattice.in
  server:
    url: "http://localhost:5000"
    description: "DEVELOPMENT SERVER"
    url: "http://157.245.100.190"
    description: "PRODUCTION SERVER"

schemes: [http, https]

# securityDefinitions:
  # BasicAuth:
  #   type: basic
  # JWT:
  #   description:
  #   type: apiKey
  #   name: Authorization
  #   in: header

host: localhost:5000
basePath: /api
paths:
  
  /register: 
    post:
      summary: create user profile
      produces:
        - application/json
      consumes:
        - application/json
      parameters: 
        - in: body
          name: user
          schema:
            type: object
            properties:
              uid: 
                type: integer
              username:
                type: string
              role:
                type: string
              pin:
                type: number
        
      responses:
        201:
          description: User profile created
          schema:
            type: object
            properties: 
              status: 
                type: integer
              message:
                type: string

        422:
          description: validation error
          schema:
            type: object
            properties: 
              status: 
                type: integer
              message:
                type: string
        409:
          description: duplicate entry
          schema:
            type: object
            properties:
              status:
                type: integer
              message:
                type: string
        500:
          description: Internal server error
          schema:
            type: object
            properties: 
              status: 
                type: integer
              message:
                type: string
        